"""Migrate Entry model

Revision ID: 8e9fec6b2296
Revises: ee334955c0e2
Create Date: 2024-07-08 20:54:25.005202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9fec6b2296'
down_revision = 'ee334955c0e2'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade_() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_entries_category_id'))

    op.drop_table('entries')
    op.drop_table('categories')
    # ### end Alembic commands ###

